apiVersion: apps/v1
kind: Deployment
metadata:
  name: yunjisuan-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yunjisuan-frontend
  template:
    metadata:
      labels:
        app: yunjisuan-frontend
    spec:
      containers:
      - name: yunjisuan-frontend
        image: yunjisuanfront:latest
        imagePullPolicy: Never  # 使用本地镜像
        ports:
        - containerPort: 5173  # 根据你的前端实际端口调整
        env:
        - name: BACKEND_URL
          value: "http://yunjisuan-backend-service:9999"
---
apiVersion: v1
kind: Service
metadata:
  name: yunjisuan-frontend-service
spec:
  selector:
    app: yunjisuan-frontend
  ports:
  - port: 5173
    targetPort: 5173
  type: LoadBalancer  # OrbStack支持LoadBalancer类型